### ISSUE TITLE
We don't know how visibility should be represented in code.

### ISSUE THREAD

**Issue by Trainzack** [Trainzack/GECLY-#6]

**Comment by GavinMK** [comment]
We make ANOTHER array that represents the visible map, which is just a grid of *'s and R's. Basically how it works is the first array, which represents the positions of objects, will be superimposed on the grid of what we can actually see according to which objects the engine determines we can see.

**Comment by Trainzack** [comment]
Wait, is this an array of booleans that is used to determine whether each particular grid point can be seen, or an array of characters that are displayed? Because the former seems more reasonable to me.
